name: Microservices CI/CD Workflow

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy_infra:
    name: Deploy Infrastructure (Dev)
    runs-on: gauravrunner

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2.3.0
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Terraform Init
        id: init
        run: terraform init -input=false
        working-directory: environments/dev

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
        working-directory: environments/dev

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color -input=false
        continue-on-error: true
        working-directory: environments/dev

      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-approve -no-color -input=false
        working-directory: environments/dev